### ISSUE TITLE
šumniki

### ISSUE THREAD

**Issue by LeaTehovnik** [LeaTehovnik/APPR-2014-15#10]
Nastavila sem si šumnike, tako kot naj bi bilo treba, a imam težave že pri preureditvi prvega grafa..
Najprej sem poiskusila samo z pdf. options in dobila to opozorilo:
Error in pdf("slike/graf1.pdf") : invalid font type
In addition: Warning messages:
1: In pdf("slike/graf1.pdf") :
  font family 'Arial' not found in PostScript font database
2: In pdf("slike/graf1.pdf") :
  font family 'Arial' not found in PostScript font database

Potem še z ukazom cairo_pdf  in še vedno ne dela, izpiše pa mi naslednjo napako:
In cairo_pdf("slike/graf1.pdf", width = 9.27, height = 11.69, family = "Arial") :
  failed to load cairo DLL

Res ne vem kaj bi bilo lahko narobe, saj sem načeloma naredila tako kot bi mogla, tudi če napišem fonts() se mi med pisavami prikaže Arial..

lp

**Comment by jaanos** [comment]
Si sledila navodilom iz `fontconfig.r`ter pognala ukaza `font_import()` in `loadfonts()`? Program `fontconfig.r` vključi tudi na začetek glavnega programa.

Glede `cairo_pdf` nisem prepričan, zakaj ne deluje - meni tako na Linuxu kot na Windowsih deluje brez problemov. Kakšen sistem pa imaš? Morda bo pomagalo, če namestiš paketa `Cairo` in `cairoDevice` ter ju nato uvoziš z `library`.

Če vseeno ne bi šlo, pusti tako, kot je - lahko poskusiš šumnike urediti na faksu, tik preden dokončaš projekt. Da ponastaviš pisavo, poženi
```R
pdf.options(family = "Helvetica")
```

**Comment by LeaTehovnik** [comment]
Sem ugotovila, da sem pozabila vključiti na začetek programa, a vseeno še ne dela.
Imam pa OS X Yosemite..

Poiskusila sem tudi namestiti paketa Cairo in cairoDevice, Cairo mi je šlo, a mi ga potem noče uvoziti z library:
Error : .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
In addition: Warning message:
package ‘Cairo’ was built under R version 3.1.2 
Error: package or namespace load failed for ‘Cairo’

cairoDevice mi pa noče namestiti :
 package ‘cairoDevice’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘cairoDevice’ is not available (for R version 3.1.1)

.. no sai bom zdaj verjetno to probala v šoli razrešiti, samo jezi me, ker ne dela.

**Comment by jaanos** [comment]
Kar se caira tiče, bo morda pomagalo, če ga posebej namestiš:

http://cairographics.org/download/

(glej pod Mac OS X za navodila za namestitev)

Brez caira pa še vedno ne deluje? Žal ne morem sam preizkusiti na Macu, zato naj @alenFMF pove, kakšne so njegove izkušnje.
