### ISSUE TITLE
prevajanje

### ISSUE THREAD

**Issue by LeaTehovnik** [LeaTehovnik/APPR-2014-15#11]
Pri prvem grafu bi rada prevedla imena držav..
To je moja originalna koda:

#drzave, kjer so manj kot trije maratonci, sem združila v druge
drzave <- table(maraton$Drzavljanstvo)
drzave <- drzave[order(drzave, decreasing=TRUE)]
druge <- drzave < 3 
drzave <- c(drzave[!druge], "Druge" = sum(drzave[druge]))
pie(drzave, main="Drzavljanstva maratoncev", clockwise = TRUE, cex = 1)

Preimenovanje sem želela naresti tako kot ste vi napisali naj naredimo, torej vektor prave ima za vrednosti drzave[!druge], za imena pa imena iz slovenska.
Problem nastane, ko želim to narisati, saj mi vrže ven:
Error in pie(drzave, main = "Drzavljanstva maratoncev", clockwise = TRUE,  : 
  'x' values must be positive.

Ugotovila sem, da je to zaradi tega, ker so v Druge NA vrednosti.. Ne vem, vse se je nekako pomešalo med sabo in ne vem kako bi to popravila..

pretvorba angleških imen v slovenska
slovenska <- c("ZDA", "Velika Britanija", "Japonska", "Kenija", "Norveška", "Etiopija",
               "Nemčija", "Avstralija", "Francija")
 prave <- drzave[!druge] names(prave)[1:9] <- slovenska
drzave <- c(prave, "Druge" = sum(drzave[druge]))
pie(drzave, main="Drzavljanstva maratoncev", clockwise = TRUE, cex = 1)

**Comment by LeaTehovnik** [comment]
Imam pa še eno vprašanje na katero upam, da mi boste znali posikati vsaj približen odgovor:)

Za zadnjo fazo sem se odločila, da bom z modelom poiskusila napovedati, kako se bo rekord spreminjal še v prihodnosti. Je to sploh mogoče? Namreč profesor mi je svetoval naj z modelom raje napovem kakšni bodo podatki po letu 1980 - torej da bi na podlaki rekordov do leta 1980 z modelom napovedala še prihodnje in bi potem pogledala, kako se kaj ujemajo z realnostjo. Sama bi sicer rada naredila oboje, imam pa pri obeh stvareh težave.

napoved za prihodnost
Tukaj imam težave, ker ne vem kako bi "podaljšala" graf, oz. kako bi rekla naj mi napove še za nekaj let naprej... Potem pa še risanje krivulje, moji podatki so čas rekorda in datum rekorda. Če probam z linearno regresijo nimam težav (lin <- lm(cas ~ datum1)), a žal moji podatki ne grejo kot premica. Zato sem želela poiskusiti še z drugimi krivuljami, a se zatakne že pri kvadratni:
kv <- lm(cas ~ I(datum1^2) + datum1)
Error in Ops.Date(datum1, 2) : ^ not defined for "Date" objects

To mi je nekako jasno zakaj je narobe, sam ne vem kako naj poindeksiram datume, da bom lahko risala krivulje?

Potem pa še, če bi napovedala iz podatkov do leta 1980. Ne vem kako naj nastavim ,da bo model upošteval samo podatke do določenega časa. Bi bilo morda v redu:
datum1[1:36] <- novdatum 
in potem to dam v krivuljo? pa seveda tudi cas[1:36] ? od 1 do 36 zato, ker 1980 na 36 mestu in me kasnejše vrednosti ne zanimajo..

Vesela bi bila vaših odgovorov, sploh tistega kako poindeksirati datume, saj bom tako morda lahko rešila še ostale težave, ker brez grafa se malo težko znajdem..

Hvala in lp

**Comment by LeaTehovnik** [comment]
No lahko bi pri datumu vzela samo letnico, samo ne vem, če je to dovolj natačno.

**Comment by LeaTehovnik** [comment]
Sedaj sem naredila tako:
datum1 <- as.Date(moski$Date, "%b %d, %Y") 
novi.datumi <- gsub("-", "", datum1)
datt <- as.numeric(novi.datumi)

in pod datt dobim stevilke, ko zaženem in posourceam mi ne javlja napak, ampak se mi nič ne izriše na graf?

Govorim sicer od datoteki vaja.R

**Comment by jaanos** [comment]
Za prevajanje bo najbolje, da si narediš en slovar in funkcijo za prevajanje, npr.
```R
slovar <- c("United States" = "ZDA",
            "United Kingdom" = "Velika Britanija",
            "Japan" = "Japonska",
            "Kenya" = "Kenija",
            "Norway" = "Norveška",
            "Ethiopia" = "Etiopija",
            "Germany" = "Nemčija",
            "Australia" = "Avstralija",
            "France" = "Francija")

prevedi <- function(x) {
  ifelse(is.na(slovar[x]), x, slovar[x])
}
```
Morda bo najbolje, če to kodo dodaš v eno novo datoteko in jo vključiš v glavni program, npr. pred uvozom. V slovar lahko dodajaš še druge nize, ki jih želiš prevajati. Funkcija `prevedi` ti vrača prevedene nize, če pa nekega niza nimaš, ga pusti takega, kot je. Potem lahko enostavno podaš prevedene oznake, npr.
```R
pie(drzave, labels = prevedi(names(drzave)),
    main="Drzavljanstva maratoncev", clockwise = TRUE, cex = 1)
```

Če želiš "podaljšati" graf, lahko to storiš s parametrom `xlim` pri ukazu `plot`, ki mu podaš meje, v katerih naj nariše os x grafa (podobno lahko z `ylim` določiš meje po osi y). Glede na to, da imaš na osi x datume, bo potrebno tudi meje podati kot datume, npr.
```R
plot(datum1, cas, main = "Spreminjanje rekorda skozi čas", xlim = as.Date(c("1908-01-01", "2050-12-31")),
     xlab = "Letnica maratona", ylab = "Čas v sekundah", type = "h", lwd = 5, col = "steelblue")
```

Izbira datumov do 1980 je načeloma v redu (seveda v obrnjenem vrstnem redu), a če bi želela dobiti prave datume neodvisno od števila podatkov (npr. če dobiš nove podatke, ki se nekoliko razlikujejo), lahko narediš
```R
novdatum <- datum1[datum1 < as.Date("1981-01-01")]
```

Če poženeš `as.numeric` na datumu, ti enostavno zbije skupaj leto, mesec in dan, tako da to ni najbolj uporabno. Bolje bo, če izbereš nek začetni datum (npr. prvega, ki se ti pojavi), potem pa delaš z razlikami (v dnevih) od tega datuma:
```R
zacetek <- min(datum1)
datt <- as.numeric(datum1 - zacetek)
```
Sedaj lahko zgradiš model, a bo potrebno pri risanju upoštevati zamik osi. Funkciji `abline` in `curve` ne delujeta najbolje z grafi na datumih, zato bo treba uporabiti funkcijo `lines`:
```R
datumi.napoved <- as.Date(paste(1908:2050, 1, 1, sep = "-")) # leta, za katera napovedujemo
linearna <- lm(cas ~ datt)
lines(datumi.napoved,
      predict(linearna, data.frame(datt=as.numeric(datumi.napoved-zacetek))),
      col = "blue")
```


Še to: ko vključuješ kodo v issue, pred njo postavi vrstico

    ```R

za njo pa

    ```

Tako se izogneš temu, da bi ti kakšne znake razumelo kot oblikovanje, obenem pa ti jo lepo pobarva (namesto `R` lahko po potrebi podaš tudi ime kakšnega drugega programskega jezika, ali pa izpustiš, da ne barva).

**Comment by LeaTehovnik** [comment]
Hvala za odgovore,imam pa še en problem, vsi te modeli (poiskusila sem z loess, kvadratno funkcijo, kubicno, cetrte stopnje) mi (razen kvadratne) sekajo abscino os še pred letom 2050, kar pa seveda ni logično. Ali obstaja kakšen način ali kakšna druga funckija, ki recimo limitira proti nič oz. vsaj proti kakšnemu bolj realnemu času, npr. 5000s (pod to mejo dvomim, da bo kdo kadarkoli pretekel 42 km) ?
Sem poiskusila z ylim omejiti y os:
```R
plot(datum1, cas, main = "Spreminjanje rekorda skozi čas", 
     xlim = as.Date(c("1908-01-01", "2050-12-31")),
     ylim = c(5000, 10518.4),
     xlab = "Letnica maratona", ylab = "Čas v sekundah", type = "h",
     lwd = 5, col = "steelblue") 
```

a mi potem zelo raztegne oz. skrči graf, je morda kakšen drug način?

Razmišljala sem, da bi uporabila še metodo voditeljev, glede na čas maratoncev,  samo ne vem kako je to smiselno, ker imam več časov iz iste države.. Imate morda Vi kakšno idejo kje bi lahko uporabila to metodo? Če sem prav razumela si ta metoda sama naključno izbere centroide? Ne vem kateri podatek bi lahko res dobila s to metodo... Je pa verjetno za 4. fazo dovolj tudi, če naredim samo analizo z regresijami?
```R
#metoda voditeljev
pdf("slike/graf7.pdf")
source("lib/uvozi.zemljevid.r")
maraton.norm <- scale(maraton$Čas)
k <- kmeans(maraton.norm, 5)
drzave <- row.names(maraton.norm)
m <- match(svet$name_long, drzave)
barve <- rainbow(5)
plot(svet, col = ifelse(is.na(m), "grey", barve[k$cluster[drzave[m]]]))

dev.off()
```

ta koda je narobe, mislim že drzave je prazen vektor, samo ne vem kaj bi sploh..

lp

**Comment by jaanos** [comment]
Lahko poskusiš zgraditi model še z `gam` - potrebno bo uvoziti knjižnico `mgcv`. Druga možnost bi bila, da bi uporabila eksponentni model. Najlažje to narediš tako, da logaritmiraš podatke na osi y, potem pa zanje zgradiš model z `lm`. Seveda bo treba pri risanju napovedi eksponencirati:
```R
logcas <- log(cas)
llin <- lm(logcas ~ datt)
lines(datumi.napoved,
      exp(predict(llin, data.frame(datt=as.numeric(datumi.napoved-zacetek)))),
      col = "blue")
```
Spodnjo mejo za os y potem prilagodi tako, da bodo lepo vidni izbrani modeli.

Kar se tiče združevanja v skupine, morda glede na tvoje podatke res ni smiselno - sploh ne, če delaš s samo enim podatkom. Če bi imela več podatkov za vsako enoto (npr. podatki o maratoncih, ali o posameznih maratonih), potem bi bilo to smiselno početi. Mislim pa, da bo zadostovala samo regresijska analiza.

Sicer pa je v zgornji kodi vektor `drzave` prazen, ker poskušaš dobiti imena vrstic iz matrike, izpeljane iz vektorja `maraton$Čas` brez imen - tudi, če bi razpredelnica `maraton` imela imena vrstic, ta vektor ne bi imel imen. Imena držav bi lahko sicer dobila enostavno iz `maraton$Drzavljanstvo`, a ker v skupine združuješ dosežke in ne države, bo na zemljevidu prikazana le barva za eno od skupin, kjer ima vsaka država dosežek.

Mimogrede, v poročilu imaš dva konflikta, ki pa ju ne bo problem odpraviti.

**Comment by LeaTehovnik** [comment]
Večino konfliktov v poročilu sem odpravila, sam še vedno se mi pa prikazuje to opozorilo:

```R
Underfull \hbox (badness 10000) in paragraph at lines 115--117
[][]$\OT1/cmtt/m/n/10.95 http : / / en . wikipedia . org / wiki / Marathon _ wo
rld _ record _
 []
```

Navajam namreč vire pa se mi ne zdi nič narobe, pdf mi tudi odpre..

```R
\newpage
\begin{thebibliography}{3}
\bibitem{1}
  \url{http://en.wikipedia.org/wiki/Marathon_world_record_progression}\\
  {Accessed: 25-02-2015}
\bibitem{2}
  \url{http://en.wikipedia.org/wiki/20th_century#Wars_and_politics}\\
  {Accessed: 25-02-2015}
```R

**Comment by jaanos** [comment]
Če dobivaš underfull hbox, ni to nič narobe - gre samo za obvestilo, da je vrstica ostala nezapolnjena.

Mimogrede, glede na to, da so tvoji podatki rekordi, je očitno, da nov rekord ne bo nikoli slabši od prejšnjega - tako bi svetoval, da izločiš modele, ki niso padajoči. Za modele, pridobljene z `lm`, v poročilu napiši tudi enačbo krivulje.

**Comment by LeaTehovnik** [comment]
O izločanju modelov sem že razmišljala, a še nisem prišla do računalnika.

Sedaj sem na faksu delno uredila zadevo s šumniki, če bom doma zagnala mi bo verjetno še vedno reklo, da je narobe ne?
Ne vem kaj je narobe, ampak šumniki mi delujejo v graf1 in graf2,  obeh zemeljevidih, problem pa nastane pri grafih analize, saj mi jih sploh ne upošteva in č kar zamenja s c.
Uproabila sem metodo cairo, ker s pdf.options ni delovalo.

```R
cairo_pdf("slike/graf4.pdf", width = 7.27, height = 5.69, family = "Arial") 


Sys.setlocale("LC_TIME", "C") # naj uporablja angleška imena mesecev:
cas.zenske <- zenske$Time
datum.zenske <- names(table(zenske$Date))
leto.zenske <- gsub(".*, ", "", datum.zenske)
names(leto.zenske) <- datum.zenske
datum1.zenske <- as.Date(zenske$Date, "%b %d, %Y") 
plot(datum1.zenske, cas.zenske, main = "Spreminjanje rekorda skozi čas", 
     xlim = as.Date(c("1918-09-29", "2050-12-31")),
     ylim = c(4000, 20400),
     xlab = "Letnica maratona", ylab = "Čas v sekundah", type = "h",
     lwd = 4, col = "pink")
```

Načeloma sem sicer zaključila s projektom, jutri zjutraj bom še šla na faks dokončati poročilo, ker mi doma  verjetno šumniki ne bodo delali, so razen poročila ostale stvari v redu?
lp

**Comment by jaanos** [comment]
Če želiš hitro preklapljati med uporabo `cairo_pdf` in `pdf`, lahko datoteko `fontconfig.r` nadomestiš s https://gist.github.com/jaanos/d304ace59a86a8c6b6a2, potem pa vse pojavitve `cairo_pdf` nadomestiš z `mypdf`. Če boš želela uporabljati `cairo_pdf`, samo odkomentiraj zadnjo vrstico v `fontconfig.r` in znova zaženi program. V glavnem programu tudi odstrani vrstico `pdf.options(family = "Arial")`.

Nisem prepričan, zakaj ti šumnikov pri tem grafu ne izpiše - pri meni deluje, sem poskusil tudi v Windowsih. Drugače pa izgleda v redu - edino pri moških rekordih odstrani še model `gam`, saj krivulja ni monotona.

Ko boš imela na GitHubu naloženo končno različico, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-2014-15-zagovori), da dodam povezavo. Obenem se s profesorjem domeni za termin zagovora.

**Comment by LeaTehovnik** [comment]
Edino to mi je čudno, da mi loess model ne napove za prihodnost, ampak samo do datuma?

**Comment by jaanos** [comment]
`loess` v bistvu zgradi model kot zglajeno krivuljo, ki ne sega izven območja, kjer imaš podatke.
