### ISSUE TITLE
Animacija

### ISSUE THREAD

**Issue by LeaTehovnik** [LeaTehovnik/APPR-2014-15#12]
Pozdravljeni, za 10 moram naresti še eno animacijo, tega sem se lotila tako, da v animacija.r delam plote za vsako leto posebej(za vsako leto se bo na državi, kjer je bil maraton postavljen, pojavil krog, če je bil večkrat, bo večji ipd.) in potem bom v latexu z 

``` R
\begin{center}
\animategraphics[controls,loop, width=1.2\linewidth]{5}{ani}{0}{6}\\
\end{center}
```

(to je samo primer za prvih 6 grafov)
naredila animacijo teh grafov. 
Imam pa dva problema, namreč ko posourcam animacija.r, mi v ani.pdf da samo prvih 6 grafov, ostalih pa sploh ne, res ne vem kaj bi lahko bilo narobe, ker samo ponavljam postopek.
Drugi je pa ta, da se mi animacija v Latexu (poiskusila sem za prvih 6 grafov npr.) sploh noče predvajati.
Hvala za vašo pomoč

**Comment by jaanos** [comment]
Zadnja dva parametra (`0` in `6` pri tebi) sta indeksa prve in zadnje strani, ki se pojavijo v animaciji. V datoteki `ani.pdf` je po zagonu programa 17 strani; če hočeš, da ti v animaciji pokaže vse, enostavno spustiš ta zadnja dva parametra (zavite oklepaje pusti!), ali pa ju ustrezno nastaviš.

Animacije morda ne bo predvajalo v vsakem prikazovalniku PDF, zagotovo pa bo delovala v Adobe Readerju (pri meni deluje).

**Comment by LeaTehovnik** [comment]
No, sem zaprla in potem zagnala še enkrat vse v adobe in mi dela, očitno je moj računalnik pač malo poseben..
Torej ,ko končam,  še enkrat odprem issue na zagovori?
To bo vejretno jutri zjutraj, bom šumnike za vsak slučaj še na šoli preverila.

**Comment by jaanos** [comment]
Tako, ko končaš, odpri nov issue.
