### ISSUE TITLE
zagon projekt.r

### ISSUE THREAD

**Issue by LeaTehovnik** [LeaTehovnik/APPR-2014-15#7]
Želela sem začet z delom na svojem računalinku, pull- ala vse iz git huba, vmes sem mela neke težave, ampak mislim, da je ok, ampak sedaj mi ob tem, ko sourcam projekt.r izpiše
važam podatke o rekordih...
Končano.
Warning messages:
1: In title(main = main, ...) :
  conversion failure on 'Državljanstva maratoncev' in 'mbcsToSbcs': dot substituted for <c5>
2: In title(main = main, ...) :
  conversion failure on 'Državljanstva maratoncev' in 'mbcsToSbcs': dot substituted for <be>
3: In title(main = main, ...) :
  conversion failure on 'Državljanstva maratoncev' in 'mbcsToSbcs': dot substituted for <c5>
4: In title(main = main, ...) :
  conversion failure on 'Državljanstva maratoncev' in 'mbcsToSbcs': dot substituted for <be>

A to obvestilo ignoriram ali je kaj narobe?

**Comment by jaanos** [comment]
To je samo opozorilo, da ti šumnikov (v naslovih grafov) ni pravilno izpisalo v PDF. Če te moti, lahko nadomestiš `"ž"` z `"z"`, lahko pa obvestilo tudi ignoriraš.
