### ISSUE TITLE
lat, long

### ISSUE THREAD

**Issue by LeaTehovnik** [LeaTehovnik/APPR-2014-15#8]
Pri izrisovanju imen držav na zemljevid sem uporabila :
imena <- c("London", "Berlin", "Paris","Tokio")
mesta <- data.frame("long" = c(51.51, 52.52, 48.85, 139.75), "lat"= c(-0.13, 13.41, 2.35,  35.68))
text(coordinates(mesta[c("long", "lat")]),
     labels = imena,
     pos= 1, cex = 0.6, offset = 0.3)

Porbelm je, ker mi Berlin, Paris in London vrže kar nekam v Ameriko. Bi morala uporabiti kakšne druge koordinate? oz. tiste z E in  W? samo mislim, d bi prišlo isto.,.

**Comment by LeaTehovnik** [comment]
Sem sedaj ugotovila ,da sta bila morda long in lat zamenjana, samo sedaj mi še vseeno ne vrže na prav mesto, London je recimo preveč spodaj. Lahko to popravim kar ročno, vstavljam številke, dokler ne pride na pravo mesto? Toxia mi pa sploh ne pokaže več..

**Comment by jaanos** [comment]
Tako je, koordinati sta bili zamenjani, razen pri Tokiu, ki je po zamenjavi padel z zemljevida (zemljepisna širina je bila večja od 90).
